### ISSUE TITLE
退款是还未开发完吗？

### ISSUE THREAD

**Issue by yuewuyan** [zeevin/cmbpayments#1]

**Comment by zeevin** [comment]
tests/refundOrder.php 这个就是退款

**Comment by yuewuyan** [comment]
Notice: Undefined index: refund in E:\xampp\htdocs\zhaobank\src\Kernel\BaseClient.php on line 149这个报错是因为我少一些配置吗

**Comment by zeevin** [comment]
抱歉，我更新了一下，你可以下载最新的再试试，我后来有些变动没提交。

**Comment by yuewuyan** [comment]
好的，好的
